In [2]:
import pandas as pd

In [8]:
data = [
    ["Alice", 25],
    ["Bob", 30],
    ["Charlie", 35]
]

df = pd.DataFrame(data)
df

         0   1
0    Alice  25
1      Bob  30
2  Charlie  35

In [9]:
data = {
    "name": ["alice", "bob", "terny"],
    "age": [3, 45, 34]
}

df2 = pd.DataFrame(data)
df2

    name  age
0  alice    3
1    bob   45
2  terny   34

In [11]:
import numpy as np

In [15]:
arr = np.array([[1,2], [3,4]])
df3 = pd.DataFrame(arr, columns = ["New", "Col"])
df3

   New  Col
0    1    2
1    3    4

In [18]:
data = pd.read_csv("data.csv")
data
data.head()

   Employee_ID           Name   Department  Salary   Join_Date
0         1001       John Doe  Engineering   85000  2022-03-15
1         1002     Jane Smith    Marketing   62000  2021-08-22
2         1003    Bob Johnson        Sales   55000  2023-01-10
3         1004    Alice Brown           HR   68000  2020-11-05
4         1005  Charlie Green      Finance   92000  2019-04-18

In [22]:
data.describe()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  10 non-null     int64
 1   Name         10 non-null     object
 2   Department   10 non-null     object
 3   Salary       10 non-null     int64
 4   Join_Date    10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

In [25]:
data2 = pd.read_csv("data.csv", usecols=["Name", "Department"])
data2

            Name   Department
0       John Doe  Engineering
1     Jane Smith    Marketing
2    Bob Johnson        Sales
3    Alice Brown           HR
4  Charlie Green      Finance
5    Emily White  Engineering
6    David Black        Sales
7     Fiona Gray    Marketing
8   George Clark      Finance
9   Hannah Adams           HR

In [28]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [30]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [32]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [36]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [38]:
df.shape

(244, 7)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB